In [15]:
import torch
import numpy as np

#Tensors on GPU/CPU

By default tensors are created on CPU:

In [2]:
tensor_cpu = torch.ones(2, 2)
tensor_cpu

tensor([[1., 1.],
        [1., 1.]])

In google colab we need to got to Runtime->Change runtime->GPU to change it.

In [3]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
#translate tensor from CPU to GPU, it overwrites original tensor
tensor_cpu.to(device)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')

In [4]:
#return to CPU
tensor_cpu.cpu()

tensor([[1., 1.],
        [1., 1.]])

#Tensor operations

In [32]:
#we can checn shape of tensor with .size()
ones = torch.ones(3, 4)
ones, ones.size()

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]), torch.Size([3, 4]))

In [33]:
#we can reshape tensor with with .view() with a valid size, 
#but it doesn't change original tensor
ones.view(2,6), ones.size(), ones.view(2,6).size()

(tensor([[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]), torch.Size([3, 4]), torch.Size([2, 6]))

In [34]:
ones.numpy()

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [35]:
integers = torch.from_numpy(np.array([[1,2,3],[4,5,6],[7,8,9]]))
integers

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

##Addition

In [36]:
# Element-wise addition
ones_new = torch.ones(integers.size())
ones_new+integers

tensor([[ 2.,  3.,  4.],
        [ 5.,  6.,  7.],
        [ 8.,  9., 10.]])

In [37]:
#or alternative
torch.add(ones_new, integers)

tensor([[ 2.,  3.,  4.],
        [ 5.,  6.,  7.],
        [ 8.,  9., 10.]])

In [38]:
#inplace addition
ones_new.add_(integers)
ones_new

tensor([[ 2.,  3.,  4.],
        [ 5.,  6.,  7.],
        [ 8.,  9., 10.]])

But...

In [39]:
integers.add_(ones_new)
integers

RuntimeError: ignored

##Subtraction, Devision, Multiplication

In [48]:
a = torch.ones(2,3)*3
b = torch.ones(2,3)
a - b

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [49]:
#not inplace
a.sub(b), a

(tensor([[2., 2., 2.],
         [2., 2., 2.]]), tensor([[3., 3., 3.],
         [3., 3., 3.]]))

In [50]:
#inplace
a.sub_(b), a

(tensor([[2., 2., 2.],
         [2., 2., 2.]]), tensor([[2., 2., 2.],
         [2., 2., 2.]]))

...the same logic with element-wise multiplication using `.mul()` or `.mul_()`

And with division using `.div()` or `.div_()`

# Mean and std

In [61]:
# generate random int betwee 0 and 10 (not inclusive)
# size should be a tuple
random_integers = torch.randint(0, 10,(3,4)).double()
random_integers

tensor([[6., 8., 4., 8.],
        [5., 2., 8., 0.],
        [0., 9., 5., 3.]], dtype=torch.float64)

In [63]:
random_integers.mean(),random_integers.mean(dim=0), random_integers.mean(dim=1)

(tensor(4.8333, dtype=torch.float64),
 tensor([3.6667, 6.3333, 5.6667, 3.6667], dtype=torch.float64),
 tensor([6.5000, 3.7500, 4.2500], dtype=torch.float64))

In [64]:
random_integers.std(),random_integers.std(dim=0), random_integers.std(dim=1)

(tensor(3.1286, dtype=torch.float64),
 tensor([3.2146, 3.7859, 2.0817, 4.0415], dtype=torch.float64),
 tensor([1.9149, 3.5000, 3.7749], dtype=torch.float64))